# Generated by Django 3.1.4 on 2021-03-05 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20210304_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='slug',
        ),
    ]
