# Generated by Django 3.1.4 on 2021-03-05 01:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_remove_lesson_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2021, 3, 5, 1, 52, 23, 890397, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
