# Generated by Django 3.1.4 on 2021-03-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_auto_20210309_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_content',
            name='code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lesson_content',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lesson_content',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
