# Generated by Django 3.1.4 on 2021-03-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_auto_20210310_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_content',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson_content',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson_content',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
