# Generated by Django 3.1.4 on 2021-03-11 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_auto_20210310_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson_content',
            options={'ordering': ['item_num']},
        ),
    ]
