# Generated by Django 3.1.7 on 2021-03-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_auto_20210310_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated'),
        ),
    ]
