# Generated by Django 3.1.7 on 2021-04-06 23:40

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_auto_20210406_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_content',
            name='body',
            field=martor.models.MartorField(blank=True, null=True),
        ),
    ]
