# Generated by Django 3.1.7 on 2021-04-13 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_auto_20210406_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('custom_key', models.IntegerField(unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['custom_key'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.chapter'),
        ),
    ]
