# Generated by Django 3.1.7 on 2021-04-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_auto_20210412_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['custom_int']},
        ),
        migrations.AlterModelOptions(
            name='lesson_content',
            options={'ordering': ['item_num'], 'verbose_name_plural': 'Lesson Contents'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='custom_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson_content',
            name='item_num',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('custom_int', 'chapter')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson_content',
            unique_together={('item_num', 'lesson')},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='custom_key',
        ),
        migrations.RemoveField(
            model_name='lesson_content',
            name='code',
        ),
    ]
